import { CategoryInfo, ProductCategory } from '@/types'

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'cosmetics',
    label: '화장품',
    laws: [
      { name: '화장품법', type: 'law' },
      { name: '화장품법 시행규칙', type: 'ordinance' },
      { name: '화장품 사용 시의 주의사항 및 알레르기 유발성분 표시에 관한 규정', type: 'notice' },
    ],
    requiredFields: [
      '명칭(제품명)',
      '영업자의 상호 및 주소',
      '제조번호',
      '사용기한 또는 개봉 후 사용기간',
      '내용량',
      '원료명',
      '사용 시 주의사항',
      '기능성화장품 표시(해당 시)',
      '제조국 표시(수입품)',
    ],
  },
  {
    id: 'food',
    label: '식품(건강기능식품)',
    laws: [
      { name: '식품등의 표시기준', type: 'notice' },
      { name: '식품등의 표시 또는 광고 실증에 관한 규정', type: 'regulation' },
      { name: '농수산물의 원산지 표시에 관한 법률', type: 'law' },
      { name: '농수산물의 원산지 표시 요령', type: 'notice' },
      { name: '건강기능식품에 관한 법률', type: 'law' },
    ],
    requiredFields: [
      '제품명',
      '식품유형',
      '업소명 및 소재지',
      '유통기한 또는 품질유지기한',
      '내용량 및 열량',
      '원재료명',
      '영양성분(해당 시)',
      '원산지',
      '주의사항',
      '보관방법',
      '기능성 내용(건강기능식품)',
    ],
  },
  {
    id: 'food_utensil',
    label: '식품용 기구·용기',
    laws: [
      { name: '식품등의 표시기준', type: 'notice' },
      { name: '식품등의 표시 또는 광고 실증에 관한 규정', type: 'regulation' },
      { name: '식품위생법', type: 'law' },
    ],
    requiredFields: [
      '재질',
      '영업소(장)의 명칭 및 소재지',
      '소비자 안전을 위한 주의사항',
      '용도(식품용)',
      '제조연월일 또는 유통기한(해당 시)',
    ],
  },
  {
    id: 'quasi_drug',
    label: '의약외품',
    laws: [
      { name: '의약외품 표시에 관한 규정', type: 'notice' },
      { name: '약사법', type: 'law' },
      { name: '약사법 시행규칙', type: 'ordinance' },
    ],
    requiredFields: [
      '품목명(제품명)',
      '성분 및 분량',
      '효능·효과',
      '용법·용량',
      '사용 시 주의사항',
      '보관방법',
      '사용기한',
      '제조번호',
      '제조업자·수입업자의 명칭 및 주소',
      '의약외품 표시',
    ],
  },
  {
    id: 'household_chemical',
    label: '생활화학제품(살생물제품)',
    laws: [
      { name: '생활화학제품 및 살생물제의 안전관리에 관한 법률', type: 'law' },
      { name: '생활화학제품 및 살생물제의 안전관리에 관한 법률 시행령', type: 'ordinance' },
      { name: '생활화학제품 및 살생물제의 안전관리에 관한 법률 시행규칙', type: 'ordinance' },
      { name: '생활화학제품 등의 표시·광고에 관한 규정', type: 'regulation' },
      { name: '안전확인대상생활화학제품 지정 및 안전·표시기준', type: 'notice' },
    ],
    requiredFields: [
      '제품명',
      '용도',
      '주요 성분명 및 함량',
      '제조자·수입자의 상호 및 주소',
      '제조국',
      '내용량',
      '사용방법',
      '사용 시 주의사항',
      '안전기준 적합 확인 표시',
      '위해성 표시(GHS 등)',
    ],
  },
  {
    id: 'electrical',
    label: '전기제품',
    laws: [
      { name: '전기용품 및 생활용품 안전관리법', type: 'law' },
      { name: '전기용품 및 생활용품 안전관리법 시행령', type: 'ordinance' },
      { name: '전기용품 및 생활용품 안전관리법 시행규칙', type: 'ordinance' },
    ],
    requiredFields: [
      '제품명(모델명)',
      '제조자·수입자명 및 주소',
      '제조국',
      '제조연월',
      '정격전압·주파수·소비전력',
      'KC 인증 표시',
      '인증번호',
      '안전·사용상 주의사항',
    ],
  },
  {
    id: 'medical_device',
    label: '의료기기',
    laws: [
      { name: '의료기기법', type: 'law' },
      { name: '의료기기법 시행령', type: 'ordinance' },
      { name: '의료기기법 시행규칙', type: 'ordinance' },
      { name: '의료기기 표시·기재 등에 관한 규정', type: 'notice' },
      { name: '의료기기 표준코드의 표시 및 관리요령', type: 'notice' },
    ],
    requiredFields: [
      '명칭(제품명·모델명)',
      '제조업자·수입업자의 상호 및 주소',
      '제조국',
      '제조번호 또는 일련번호',
      '제조연월일 또는 사용기한',
      '품목허가(신고) 번호',
      '사용목적(효능·효과)',
      '사용방법',
      '사용 시 주의사항',
      '저장방법·사용기간',
      'UDI(표준코드) 표시',
    ],
  },
]

export function getCategoryInfo(id: ProductCategory): CategoryInfo | undefined {
  return CATEGORIES.find((c) => c.id === id)
}
